services:
  - type: web
    name: puppeteer-screenshot-server
    env: node
    plan: starter
    buildCommand: npm ci
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: "20.12.2"
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer