services:
  - type: web
    name: puppeteer-screenshot-server
    env: node
    plan: starter

    # 1) install Chromium with apt
    # 2) install Node deps
    buildCommand: |
      apt-get update -y
      apt-get install -y chromium chromium-common fonts-liberation
      npm ci

    startCommand: node server.js

    envVars:
      - key: NODE_VERSION
        value: "20.12.2"